name: doctor_app
description: Doctor App for Lab Mid Activity
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8
  path: ^1.8.4
  path_provider: ^2.0.14
  image_picker: ^0.8.7+5
  file_picker: ^5.2.5
  open_filex: ^4.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  assets:
    - assets/logo1.jpg
    - assets/1.png
    - assets/2.png
    - assets/3.png

